version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-lts
    container_name: sqlserver_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MinhaSenha@2025
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql
    restart: unless-stopped